php-fpm:
    build: php-fpm
    container_name: cdn_fpm_app
    ports:
        - 9000:9000
    volumes:
        - ./app:/var/www/html/
        - ./images:/var/www/images
nginx_app:
    build: nginx_app
    container_name: cdn_nginx_app
    ports:
        - 127.0.0.1:8080:80
    volumes:
        - ./app:/var/www/html/
    links:
        - php-fpm
nginx_front:
    build: nginx_front
    container_name: cdn_nginx_front
    ports:
        - 127.0.0.1:80:80
    volumes:
        - ./images:/var/www/images