php-fpm:
    build: php-fpm
    ports:
        - 9000:9000
    volumes:
        - ./app:/var/www/html/
        - ./images:/var/www/images
nginx_app:
    build: nginx_app
    ports:
        - 8080:80
    volumes:
        - ./app:/var/www/html/
    links:
        - php-fpm
nginx_front:
    build: nginx_front
    ports:
        - 8081:80
    volumes:
        - ./images:/var/www/images